import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { QueryProviders } from '@/context/QueryProvider'
import '@/res/css/globals.css'
import { NextLayout } from './providers'

const globalFont = localFont({
  src: './_font/NotoSansKR-VariableFont_wght.ttf',
  display: 'swap',
})

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: '랭킹킹',
    description: 'Generated by create next app',
    icons: {
      icon: '/favicon.ico',
    },
    //TODO: Add openGraph images
    //openGraph: {
    //  images: ['/some-specific-page-image.jpg', ...previousImages],
    //},
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body className={globalFont.className}>
        <QueryProviders>
          <NextLayout>{children}</NextLayout>
        </QueryProviders>
      </body>
    </html>
  )
}
